<?php

use Illuminate\Database\Seeder;

class CompanyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('company')->delete();
        
        \DB::table('company')->insert(array (
            0 => 
            array (
                'company_id' => 1,
                'nickname' => '取引先１',
                'fullname' => '株式会社　取引先１',
                'is_customer' => 1,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 1,
                'closing_day' => 1,
                'payment' => 1,
                'payment_day' => 1,
                'zip' => '874-0034',
                'address' => '大分県別府市上人仲町1-1',
                'tel' => '0978-44-0077',
                'fax' => '0978-44-0088',
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'company_id' => 2,
                'nickname' => '宇佐建機',
                'fullname' => '宇佐建機',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 2,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:40:09',
                'updated_at' => '2019-12-14 15:40:09',
            ),
            2 => 
            array (
                'company_id' => 3,
                'nickname' => 'さとう建設',
                'fullname' => 'さとう建設',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            3 => 
            array (
                'company_id' => 4,
                'nickname' => '大和建材',
                'fullname' => '大和建材',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            4 => 
            array (
                'company_id' => 5,
                'nickname' => '別府商事',
                'fullname' => '別府商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 4,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            5 => 
            array (
                'company_id' => 6,
                'nickname' => 'あいおい商店',
                'fullname' => 'あいおい商店',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 4,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            6 => 
            array (
                'company_id' => 7,
                'nickname' => '大分建材',
                'fullname' => '大分建材',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            7 => 
            array (
                'company_id' => 8,
                'nickname' => '秋月建設',
                'fullname' => '秋月建設',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            8 => 
            array (
                'company_id' => 9,
                'nickname' => '中津建材',
                'fullname' => '中津建材',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            9 => 
            array (
                'company_id' => 10,
                'nickname' => 'ふそうリース',
                'fullname' => 'ふそうリース',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            10 => 
            array (
                'company_id' => 11,
                'nickname' => '大和商事',
                'fullname' => '大和商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            11 => 
            array (
                'company_id' => 12,
                'nickname' => '秋月商店',
                'fullname' => '秋月商店',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            12 => 
            array (
                'company_id' => 13,
                'nickname' => '双葉建機',
                'fullname' => '双葉建機',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            13 => 
            array (
                'company_id' => 14,
                'nickname' => '三和商事',
                'fullname' => '三和商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 2,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            14 => 
            array (
                'company_id' => 15,
                'nickname' => 'すずき建機',
                'fullname' => 'すずき建機',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            15 => 
            array (
                'company_id' => 16,
                'nickname' => '双葉建機',
                'fullname' => '双葉建機',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            16 => 
            array (
                'company_id' => 17,
                'nickname' => 'ふそう商事',
                'fullname' => 'ふそう商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            17 => 
            array (
                'company_id' => 18,
                'nickname' => '別府建材',
                'fullname' => '別府建材',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            18 => 
            array (
                'company_id' => 19,
                'nickname' => '扶桑建設',
                'fullname' => '扶桑建設',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            19 => 
            array (
                'company_id' => 20,
                'nickname' => '三浦建材',
                'fullname' => '三浦建材',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 1,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            20 => 
            array (
                'company_id' => 21,
                'nickname' => '大分土木',
                'fullname' => '大分土木',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            21 => 
            array (
                'company_id' => 22,
                'nickname' => '双葉商事',
                'fullname' => '双葉商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 2,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            22 => 
            array (
                'company_id' => 23,
                'nickname' => '三浦建機',
                'fullname' => '三浦建機',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            23 => 
            array (
                'company_id' => 24,
                'nickname' => '双葉リース',
                'fullname' => '双葉リース',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 3,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            24 => 
            array (
                'company_id' => 25,
                'nickname' => '大和土木',
                'fullname' => '大和土木',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            25 => 
            array (
                'company_id' => 26,
                'nickname' => 'ふそう商事',
                'fullname' => 'ふそう商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            26 => 
            array (
                'company_id' => 27,
                'nickname' => '中津土木',
                'fullname' => '中津土木',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            27 => 
            array (
                'company_id' => 28,
                'nickname' => '双葉リース',
                'fullname' => '双葉リース',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            28 => 
            array (
                'company_id' => 29,
                'nickname' => '三友商事',
                'fullname' => '三友商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            29 => 
            array (
                'company_id' => 30,
                'nickname' => '秋月土木',
                'fullname' => '秋月土木',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            30 => 
            array (
                'company_id' => 31,
                'nickname' => '三浦商事',
                'fullname' => '三浦商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            31 => 
            array (
                'company_id' => 32,
                'nickname' => 'さとう商事',
                'fullname' => 'さとう商事',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            32 => 
            array (
                'company_id' => 33,
                'nickname' => '三和建設',
                'fullname' => '三和建設',
                'is_customer' => 0,
                'is_subcon' => 0,
                'is_own' => 0,
                'closing' => 0,
                'closing_day' => 0,
                'payment' => 0,
                'payment_day' => 0,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-14 15:41:41',
                'updated_at' => '2019-12-14 15:41:41',
            ),
            33 => 
            array (
                'company_id' => 34,
                'nickname' => '辻田建機',
                'fullname' => '有限会社　辻田建機',
                'is_customer' => 0,
                'is_subcon' => 1,
                'is_own' => 1,
                'closing' => 2,
                'closing_day' => NULL,
                'payment' => 0,
                'payment_day' => NULL,
                'zip' => NULL,
                'address' => NULL,
                'tel' => NULL,
                'fax' => NULL,
                'user_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-18 09:11:37',
                'updated_at' => '2020-01-18 09:11:37',
            ),
        ));
        
        
    }
}