<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'item_id' => 1,
                'item_name' => '10cmブロック',
                'item_type' => 1,
                'def_price' => 1000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'item_id' => 2,
                'item_name' => '10ｌガソリン缶',
                'item_type' => 2,
                'def_price' => 31620000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'item_id' => 3,
                'item_name' => '１５cmブロック',
                'item_type' => 1,
                'def_price' => 1570000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'item_id' => 4,
                'item_name' => '16クリップアンカー',
                'item_type' => 1,
                'def_price' => 2230000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'item_id' => 5,
                'item_name' => '1tローラー',
                'item_type' => 3,
                'def_price' => 23600000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'item_id' => 6,
                'item_name' => '１t土嚢袋',
                'item_type' => 1,
                'def_price' => 4900000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'item_id' => 7,
                'item_name' => '1コ刃',
                'item_type' => 1,
                'def_price' => 25000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'item_id' => 8,
                'item_name' => '20Lガソリンタンク',
                'item_type' => 1,
                'def_price' => 34000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'item_id' => 9,
                'item_name' => '20L容器',
                'item_type' => 1,
                'def_price' => 10660000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'item_id' => 10,
                'item_name' => '25tラフタークレーン',
                'item_type' => 3,
                'def_price' => 500000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'item_id' => 11,
                'item_name' => '２tダンプ',
                'item_type' => 3,
                'def_price' => 40000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'item_id' => 12,
                'item_name' => '2サイクルオイル',
                'item_type' => 2,
                'def_price' => 6000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'item_id' => 13,
                'item_name' => '４tキャリー',
                'item_type' => 3,
                'def_price' => 208000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'item_id' => 14,
            'item_name' => '４tキャリー(調整金)',
                'item_type' => 3,
                'def_price' => 8000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'item_id' => 15,
                'item_name' => '４tダンプ',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'item_id' => 16,
                'item_name' => '４tユニック',
                'item_type' => 3,
                'def_price' => 40000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'item_id' => 17,
                'item_name' => '４tローラ',
                'item_type' => 3,
                'def_price' => 540000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'item_id' => 18,
                'item_name' => '4tローラ',
                'item_type' => 3,
                'def_price' => 50000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'item_id' => 19,
                'item_name' => '５mmワイヤー',
                'item_type' => 1,
                'def_price' => 1300000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'item_id' => 20,
                'item_name' => '652T5K',
                'item_type' => 1,
                'def_price' => 14020000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'item_id' => 21,
                'item_name' => '75VPP',
                'item_type' => 3,
                'def_price' => 35950000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'item_id' => 22,
                'item_name' => '８インチ水中ポンプ',
                'item_type' => 3,
                'def_price' => 180000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'item_id' => 23,
                'item_name' => '9トラロープ',
                'item_type' => 1,
                'def_price' => 13320000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'item_id' => 24,
                'item_name' => 'BH0.2',
                'item_type' => 3,
                'def_price' => 26330000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'item_id' => 25,
                'item_name' => 'BH0.3',
                'item_type' => 3,
                'def_price' => 40000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'item_id' => 26,
                'item_name' => 'BH0.45',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'item_id' => 27,
                'item_name' => 'BH0.5',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'item_id' => 28,
                'item_name' => 'BH0.7',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'item_id' => 29,
                'item_name' => 'DT4',
                'item_type' => 3,
                'def_price' => 114000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'item_id' => 30,
                'item_name' => 'M-30',
                'item_type' => 1,
                'def_price' => 28000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'item_id' => 31,
                'item_name' => 'PEテープ',
                'item_type' => 1,
                'def_price' => 3090000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'item_id' => 32,
                'item_name' => 'PPロープ',
                'item_type' => 1,
                'def_price' => 16640000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'item_id' => 33,
                'item_name' => 'RC-40',
                'item_type' => 1,
                'def_price' => 36000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'item_id' => 34,
                'item_name' => 'VP200（三相）',
                'item_type' => 3,
                'def_price' => 12500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'item_id' => 35,
                'item_name' => 'アイボルト',
                'item_type' => 1,
                'def_price' => 2850000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'item_id' => 36,
                'item_name' => 'アスガラ処分',
                'item_type' => 1,
                'def_price' => 120000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'item_id' => 37,
                'item_name' => 'アンカー',
                'item_type' => 1,
                'def_price' => 450000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'item_id' => 38,
                'item_name' => 'エアーピック',
                'item_type' => 3,
                'def_price' => 65000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'item_id' => 39,
                'item_name' => 'エアホース',
                'item_type' => 1,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'item_id' => 40,
                'item_name' => 'エンジンカッター',
                'item_type' => 3,
                'def_price' => 51000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'item_id' => 41,
                'item_name' => 'エンジンブロア',
                'item_type' => 3,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'item_id' => 42,
                'item_name' => 'オールフィッツジョイント３０００',
                'item_type' => 1,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'item_id' => 43,
                'item_name' => 'かき板',
                'item_type' => 1,
                'def_price' => 8800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'item_id' => 44,
                'item_name' => 'ガソリン',
                'item_type' => 2,
                'def_price' => 1480000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'item_id' => 45,
                'item_name' => 'カッター',
                'item_type' => 1,
                'def_price' => 3990000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'item_id' => 46,
                'item_name' => 'かなてこ',
                'item_type' => 1,
                'def_price' => 65000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'item_id' => 47,
                'item_name' => 'キャップタイヤ',
                'item_type' => 1,
                'def_price' => 250000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'item_id' => 48,
                'item_name' => 'キラク',
                'item_type' => 1,
                'def_price' => 140000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'item_id' => 49,
                'item_name' => 'クロー',
                'item_type' => 1,
                'def_price' => 72000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'item_id' => 50,
                'item_name' => 'ゲッターパイル',
                'item_type' => 1,
                'def_price' => 3000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'item_id' => 51,
                'item_name' => 'コノエダブル',
                'item_type' => 1,
                'def_price' => 28000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'item_id' => 52,
                'item_name' => 'コノエネイル',
                'item_type' => 1,
                'def_price' => 13610000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'item_id' => 53,
                'item_name' => 'コンクリート',
                'item_type' => 1,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'item_id' => 54,
                'item_name' => 'コンクリートガラ',
                'item_type' => 1,
                'def_price' => 10000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'item_id' => 55,
                'item_name' => 'コンテナハウス・トイレ・倉庫',
                'item_type' => 3,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'item_id' => 56,
                'item_name' => 'コンパネ　',
                'item_type' => 1,
                'def_price' => 8800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'item_id' => 57,
                'item_name' => 'コンプレッサー　',
                'item_type' => 3,
                'def_price' => 0,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'item_id' => 58,
                'item_name' => 'サクションホース',
                'item_type' => 1,
                'def_price' => 12000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'item_id' => 59,
                'item_name' => 'さげふり',
                'item_type' => 1,
                'def_price' => 9800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'item_id' => 60,
                'item_name' => 'サニーホース',
                'item_type' => 1,
                'def_price' => 1000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'item_id' => 61,
                'item_name' => 'サニーホース200',
                'item_type' => 1,
                'def_price' => 7500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'item_id' => 62,
                'item_name' => 'しガラネット',
                'item_type' => 1,
                'def_price' => 10200000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'item_id' => 63,
                'item_name' => 'シャックル',
                'item_type' => 1,
                'def_price' => 12520000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'item_id' => 64,
                'item_name' => 'スプレー',
                'item_type' => 1,
                'def_price' => 5050000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'item_id' => 65,
                'item_name' => 'スリム看板',
                'item_type' => 1,
                'def_price' => 10000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'item_id' => 66,
                'item_name' => 'ゼブラテープ',
                'item_type' => 1,
                'def_price' => 2660000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'item_id' => 67,
                'item_name' => 'トイレットペーパー',
                'item_type' => 1,
                'def_price' => 3690000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'item_id' => 68,
                'item_name' => 'トイレブラシ',
                'item_type' => 1,
                'def_price' => 11540000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'item_id' => 69,
                'item_name' => 'トラロープ',
                'item_type' => 1,
                'def_price' => 13190000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'item_id' => 70,
                'item_name' => 'トン袋',
                'item_type' => 1,
                'def_price' => 8300000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'item_id' => 71,
                'item_name' => 'にーどふマット',
                'item_type' => 1,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'item_id' => 72,
                'item_name' => 'のこ刃',
                'item_type' => 1,
                'def_price' => 13660000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'item_id' => 73,
                'item_name' => 'ノミ',
                'item_type' => 1,
                'def_price' => 22000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'item_id' => 74,
                'item_name' => 'パイプ・クランプ',
                'item_type' => 1,
                'def_price' => 25000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'item_id' => 75,
                'item_name' => 'パイプサポート',
                'item_type' => 1,
                'def_price' => 2800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'item_id' => 76,
                'item_name' => 'ハイロッド',
                'item_type' => 1,
                'def_price' => 14180000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'item_id' => 77,
                'item_name' => 'ハウス',
                'item_type' => 1,
                'def_price' => 3340000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'item_id' => 78,
                'item_name' => 'ハケ',
                'item_type' => 1,
                'def_price' => 3450000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'item_id' => 79,
                'item_name' => 'BH0.15',
                'item_type' => 3,
                'def_price' => 84000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'item_id' => 80,
                'item_name' => 'BH0.08',
                'item_type' => 3,
                'def_price' => 62800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'item_id' => 81,
                'item_name' => 'ビニールテープ',
                'item_type' => 1,
                'def_price' => 550000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'item_id' => 82,
                'item_name' => 'ビニルパイプvp',
                'item_type' => 1,
                'def_price' => 6500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'item_id' => 83,
                'item_name' => 'ピンボール',
                'item_type' => 1,
                'def_price' => 3710000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'item_id' => 84,
                'item_name' => 'ブルーシート#3000',
                'item_type' => 1,
                'def_price' => 9500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'item_id' => 85,
                'item_name' => 'プレート',
                'item_type' => 1,
                'def_price' => 10600000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'item_id' => 86,
                'item_name' => 'ブロック（12ｃｍ）',
                'item_type' => 1,
                'def_price' => 1320000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'item_id' => 87,
                'item_name' => 'ペンキ',
                'item_type' => 1,
                'def_price' => 37250000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'item_id' => 88,
                'item_name' => 'ポリ容器',
                'item_type' => 1,
                'def_price' => 8180000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'item_id' => 89,
                'item_name' => 'マーカー',
                'item_type' => 1,
                'def_price' => 6600000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'item_id' => 90,
                'item_name' => 'マジックシート',
                'item_type' => 1,
                'def_price' => 5080000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'item_id' => 91,
                'item_name' => 'マスキングテープ',
                'item_type' => 1,
                'def_price' => 2690000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'item_id' => 92,
                'item_name' => 'ライン石灰',
                'item_type' => 1,
                'def_price' => 6320000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'item_id' => 93,
                'item_name' => 'レギュラーガソリン',
                'item_type' => 2,
                'def_price' => 1350000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'item_id' => 94,
                'item_name' => 'レギュラーガソリン（59-44）',
                'item_type' => 2,
                'def_price' => 1480000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'item_id' => 95,
                'item_name' => 'ワイヤクリップ',
                'item_type' => 1,
                'def_price' => 750000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'item_id' => 96,
                'item_name' => '安全掲示板',
                'item_type' => 1,
                'def_price' => 28000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'item_id' => 97,
                'item_name' => '運搬費',
                'item_type' => 1,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'item_id' => 98,
                'item_name' => '温度計',
                'item_type' => 1,
                'def_price' => 40000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'item_id' => 99,
                'item_name' => '下地合板',
                'item_type' => 1,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'item_id' => 100,
                'item_name' => '仮設トイレ',
                'item_type' => 3,
                'def_price' => 3340000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'item_id' => 101,
                'item_name' => '巻き尺',
                'item_type' => 4,
                'def_price' => 103160000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'item_id' => 102,
                'item_name' => '看板　',
                'item_type' => 4,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'item_id' => 103,
                'item_name' => '吉良田',
                'item_type' => 1,
                'def_price' => 17500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'item_id' => 104,
                'item_name' => '吸出し防止材',
                'item_type' => 1,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'item_id' => 105,
                'item_name' => '軽油',
                'item_type' => 2,
                'def_price' => 1230000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'item_id' => 106,
            'item_name' => '軽油(2tダンプ)',
                'item_type' => 2,
                'def_price' => 1100000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'item_id' => 107,
            'item_name' => '軽油(重機用)',
                'item_type' => 2,
                'def_price' => 1100000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'item_id' => 108,
                'item_name' => '工具倉庫',
                'item_type' => 3,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'item_id' => 109,
                'item_name' => '杭',
                'item_type' => 1,
                'def_price' => 6500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'item_id' => 110,
                'item_name' => '高速カッター刃',
                'item_type' => 4,
                'def_price' => 38000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'item_id' => 111,
                'item_name' => '黒板',
                'item_type' => 4,
                'def_price' => 41000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'item_id' => 112,
                'item_name' => '差し筋アンカ　',
                'item_type' => 4,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'item_id' => 113,
                'item_name' => '砂',
                'item_type' => 1,
                'def_price' => 1500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'item_id' => 114,
                'item_name' => '砂',
                'item_type' => 1,
                'def_price' => 1500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'item_id' => 115,
                'item_name' => '砕石M-30',
                'item_type' => 1,
                'def_price' => 28000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'item_id' => 116,
                'item_name' => '坂本',
                'item_type' => 4,
                'def_price' => 18000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'item_id' => 117,
                'item_name' => '三角旗',
                'item_type' => 4,
                'def_price' => 3000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'item_id' => 118,
                'item_name' => '重機回送',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'item_id' => 119,
            'item_name' => '重機回送BH0.3(自社)',
                'item_type' => 3,
                'def_price' => 270000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'item_id' => 120,
                'item_name' => '重機回送BH0.45',
                'item_type' => 3,
                'def_price' => 250000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'item_id' => 121,
                'item_name' => '重機回送費',
                'item_type' => 3,
                'def_price' => 60000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'item_id' => 122,
                'item_name' => '重機回送費BH0.15',
                'item_type' => 3,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'item_id' => 123,
                'item_name' => '水タンク',
                'item_type' => 4,
                'def_price' => 8900000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'item_id' => 124,
                'item_name' => '水糸',
                'item_type' => 1,
                'def_price' => 5610000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'item_id' => 125,
                'item_name' => '水中ポンプ2寸',
                'item_type' => 3,
                'def_price' => 2500000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'item_id' => 126,
                'item_name' => '水中ポンプ8インチ+ケーブル',
                'item_type' => 3,
                'def_price' => 291850000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'item_id' => 127,
                'item_name' => '水中ポンプ管理料',
                'item_type' => 3,
                'def_price' => 2000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'item_id' => 128,
                'item_name' => '製材チョーク',
                'item_type' => 1,
                'def_price' => 800000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'item_id' => 129,
                'item_name' => '赤白丁張',
                'item_type' => 4,
                'def_price' => 30000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'item_id' => 130,
                'item_name' => '説明看板（無反射）枠付',
                'item_type' => 4,
                'def_price' => 25000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'item_id' => 131,
                'item_name' => '草刈り機',
                'item_type' => 3,
                'def_price' => 50000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'item_id' => 132,
                'item_name' => '草刈り機　刃',
                'item_type' => 1,
                'def_price' => 24150000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'item_id' => 133,
            'item_name' => '草刈り機(刃)',
                'item_type' => 1,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'item_id' => 134,
                'item_name' => '草刈り刃',
                'item_type' => 1,
                'def_price' => 6490000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'item_id' => 135,
                'item_name' => '耐水マーカー',
                'item_type' => 1,
                'def_price' => 2140000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'item_id' => 136,
                'item_name' => '大型土嚢袋',
                'item_type' => 1,
                'def_price' => 4900000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'item_id' => 137,
                'item_name' => '単管標識',
                'item_type' => 1,
                'def_price' => 8000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'item_id' => 138,
                'item_name' => '竹ほうき',
                'item_type' => 4,
                'def_price' => 24380000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'item_id' => 139,
                'item_name' => '竹ほーき',
                'item_type' => 4,
                'def_price' => 6610000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'item_id' => 140,
                'item_name' => '丁型レンチ',
                'item_type' => 4,
                'def_price' => 4570000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'item_id' => 141,
                'item_name' => '丁張板',
                'item_type' => 4,
                'def_price' => 8000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'item_id' => 142,
                'item_name' => '吊りフック',
                'item_type' => 4,
                'def_price' => 23000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'item_id' => 143,
                'item_name' => '鉄筋',
                'item_type' => 1,
                'def_price' => 25000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'item_id' => 144,
                'item_name' => '鉄筋カッター',
                'item_type' => 4,
                'def_price' => 26000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'item_id' => 145,
                'item_name' => '鉄骨ビス',
                'item_type' => 1,
                'def_price' => 4010000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'item_id' => 146,
                'item_name' => '土嚢袋',
                'item_type' => 1,
                'def_price' => 12000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'item_id' => 147,
                'item_name' => '認識テープ',
                'item_type' => 1,
                'def_price' => 7140000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'item_id' => 148,
                'item_name' => '発電機',
                'item_type' => 3,
                'def_price' => 6400000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'item_id' => 149,
                'item_name' => '被覆番線',
                'item_type' => 1,
                'def_price' => 6950000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'item_id' => 150,
                'item_name' => '敷鉄板',
                'item_type' => 1,
                'def_price' => 250000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'item_id' => 151,
                'item_name' => '幅広テープ',
                'item_type' => 1,
                'def_price' => 3680000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'item_id' => 152,
                'item_name' => '平ゴム',
                'item_type' => 1,
                'def_price' => 1530000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'item_id' => 153,
                'item_name' => '補助アンカー',
                'item_type' => 1,
                'def_price' => 65000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'item_id' => 154,
                'item_name' => '面取り機',
                'item_type' => 4,
                'def_price' => 25000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'item_id' => 155,
                'item_name' => '輸入シート',
                'item_type' => 1,
                'def_price' => 3300000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'item_id' => 156,
                'item_name' => '輸入シート3.6*5.4',
                'item_type' => 1,
                'def_price' => 3300000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'item_id' => 157,
                'item_name' => '有筋コンクリートガラ',
                'item_type' => 1,
                'def_price' => 15000000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'item_id' => 158,
                'item_name' => '養生テープ',
                'item_type' => 1,
                'def_price' => 6860000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'item_id' => 159,
            'item_name' => '腕章(11/1)',
                'item_type' => 4,
                'def_price' => 3900000,
                'user_id' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}